# Generated by Django 3.0.5 on 2020-04-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200407_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='koica_code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department', to='users.Department'),
        ),
    ]
