# Generated by Django 3.0.5 on 2020-04-07 08:09

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200407_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='workon_countries',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
    ]
