# Generated by Django 3.0.5 on 2020-04-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_field',
        ),
        migrations.AddField(
            model_name='article',
            name='sector',
            field=models.CharField(choices=[('rc', '수원국'), ('dn', '공여국'), ('in', '국제기구'), ('ko', 'KOICA')], default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='subject_type',
            field=models.CharField(choices=[('edu', '교육'), ('hea', '보건의료'), ('gov', '공공행정'), ('agr', '농림수산'), ('tec', '기술환경에너지'), ('emr', '긴급구호'), ('etc', '기타')], max_length=16),
        ),
    ]
